#----------------------
# About section

blurb: </strong> I am a Ph.D. candidate in <a href="http://www.stat.ncsu.edu" target="_blank">Deparment of Statistics</a> at North Carolina State University advised by <a href="http://www4.stat.ncsu.edu/~bloomfld/" target="_blank"> Peter Bloomfield</a> and <a href="http://www4.stat.ncsu.edu/~sghosal/" target="_blank">Subhashis Ghoshal</a>. My research interests are Bayesian analysis, time series analysis, variable selection and causal inference. 

#----------------------
# Courses section
courses:
  - {title: Intro to Chem, semester: Fall 1885, school: King's College London, description: Teaching students chemistry isn't only for witches., link: courses/temp_course }
  - {title: Advanced Psychiatric Medicine, semester: Spring 1885, school: King's College London, description: At the time, mainly lobotomy., link: courses/temp_course }
  - {title: Diseases of the Mind, semester: Fall 1884, school: King's College London, description: Survey course. Mainly taught by example., link: courses/temp_course }
#----------------------
# Contact
contact-info: <p>209 BOM<br>Department of Statistics<br>NC State University<br>Raleigh, NC 27695<br><a href="mailto:bning@ncsu.edu"targe="_top">bning@ncsu.edu</a></p>

contact-links:
  - {contact-text: Github, contact-link: "https://www.github.com/Bo-Ning?tab=repositories", icon: 'favicon.html'}
